### ISSUE TITLE
高手，刷题库要什么步骤呢

### ISSUE THREAD

**Issue by 85524365** [wanghuisenior/auto_xxqg#10]
感谢大神分享脚本，除了订阅，偶尔红字报错，但自动跳过去了，今天一次性顺畅学完46分，毫不便秘，一个爽字怎么了得！佩服佩服
再请教一下，刷题库需要怎么操作呢

**Comment by wanghuisenior** [comment]
开启无限答题，然后去每日或者挑战，点手动答题。只支持每日或者挑战

**Comment by 85524365** [comment]
感谢膜拜
