### ISSUE TITLE
请问多账户怎么添加，然后自动登录学习啊？

### ISSUE THREAD

**Issue by hanguowei98** [wanghuisenior/auto_xxqg#12]

**Comment by hanguowei98** [comment]
怎么在config.txt文件上加账号，让几个账号按顺序自动切换登录？

**Comment by wanghuisenior** [comment]
![image](https://user-images.githubusercontent.com/9377248/104076549-5366b280-5251-11eb-93ed-911182dcbf86.png)

**Comment by wanghuisenior** [comment]
{
  "users": [
    {
      "username": "18888888888",
      "password": "88888888"
    },
    {
      "username": "18888888888",
      "password": "88888888"
    },
    {
      "username": "18888888888",
      "password": "88888888"
    },
    {
      "username": "18888888888",
      "password": "88888888"
    },
  ],
  "url": "http://pushplus.hxtrip.com/send",
  "token": "de17144cb3be48608fbfea27a5ef0b90",
  "wxpost": 0,
  "article": "推荐",
  "update2server": 0,
  "forever": 0,
  "weekdt": 1,
  "specialdt": 1
}

**Comment by hanguowei98** [comment]
@wanghuisenior    谢谢！
