### ISSUE TITLE
成功订阅部分代码。。。。

### ISSUE THREAD

**Issue by hanguowei98** [wanghuisenior/auto_xxqg#13]
1.!xxqg_v3.1.3(fixall).js  文件部分

//    var asub = 2; //订阅数 // 注释掉
//........................
//    subScribe = 2 - myScores["订阅"]; // 注释掉

//........................
/*************************************************订阅部分***************************************************/
/**
/**
 * @description: 订阅强国号
 * @param  null
 * @return: null
 */
function Subscription() {
    var listView = className("android.view.View").depth(13).findOnce(1);
    var listArray = listView.children();
    //console.log(listArray[1].child(1).text());

    var delayTime = 120;
    var myColor = "#e32416";
    //var myColor = "#f2f3f5";
    var myThreshold = 4;
    var isName = "";
    while (true) {
        if (isName == listArray[2].child(1).text()) {
            break;
        }
        // console.hide(); //隐藏console控制台窗口
        sleep(delayTime); //等待截屏
        var img = captureScreen(); //截个屏
        // captureScreen("./ddd.png");//截个屏
        // var img = images.read("./ddd.png");
        // console.show(); //显示console控制台窗口

        isName = listArray[2].child(1).text();
        var isFind = false;
        listArray.some(item => {
            // let isSub = isSubscription(delayTime, myColor, myThreshold, item.child(2));

            if (item.children().length > 2) {
                //console.log(item.child(1).text());
                var listBounds = item.child(2).bounds();
                // console.log(listBounds);
                var point = findColor(img, myColor, {
                    region: [listBounds.left, listBounds.top, listBounds.right - listBounds.left, listBounds.bottom - listBounds.top],
                    threshold: myThreshold
                });
                if (point) {
                    // console.log(item.child(1).text());
                    console.log("已订阅");
                    item.child(2).click();
                    isFind = true;
                    sleep(1000)
                    return true;
                } else {
                    // return false;
                }
            }
            //displayColor(item.child(2).bounds().centerX() + 5, item.child(2).bounds().centerY() + 5);
        });
        if (!isFind) {
            listView.scrollForward();
            sleep(100);
            //console.error("滑动");
            listView = className("android.view.View").depth(13).findOnce(1);
            listArray = listView.children();
            if (isName == listArray[2].child(1).text()) {
                listView.scrollForward();
                //console.warn("滑动2");
                listView = className("android.view.View").depth(13).findOnce(1);
                listArray = listView.children();
            }
        }
        sleep(100);
    }
    return isFind;
}
/**
@description: 学习平台订阅
@param: null
@return: null
*/
function subScribe() {
    h = device.height; //屏幕高
    w = device.width; //屏幕宽
    x = (w / 3) * 2; //横坐标2分之3处
    h1 = (h / 6) * 5; //纵坐标6分之5处
    h2 = (h / 6); //纵坐标6分之1处
    while (!desc("工作").exists()); //等待加载出主页
    desc("工作").click();
    console.log('正在订阅...');
    click("订阅");
    sleep(random(1000, 2000)); 
    className("android.support.v7.widget.RecyclerView").findOne().children().findOne(className("android.widget.TextView")).parent().click();
    sleep(random(1000, 2000));
    click("上新");
    //click("主要央媒");
    sleep(random(1000, 2000));
    // click("强国号",0);
    // console.log(className("android.widget.ListView").findOnce(0));
    // var listView = className("android.widget.ListView").findOnce(0); //获取listView视频列表控件用于翻页
    var i = myScores["订阅"];
    // console.log("订阅：" + i);
    i = 0
    let falseNumber = 0; 
    let isSub = false;
    while (i < 2) {
        isSub = Subscription();
        // console.log(isSub);
        if (isSub) {
            i++;
        } else {
            //break;
            falseNumber++;
            //click("推荐");
            //sleep(1000);
        }
        if (falseNumber > 2) {
            console.log("没有可订阅的强国号");
            break;
        }
    }
    back();
    //while (!desc("工作").exists());
    desc("工作").click();
    // click("时评");
    sleep(1000);
}
/*************************************************订阅部分结束***************************************************/
/**

//........................

function xx3() {
    let curr_time = new Date();
    let weekNum = curr_time.getDay();
    // console.log('weekday:' + weekNum);
    if (myScores['订阅'] < 2 && weekNum < 8) {
        subScribe(); //订阅学习平台
    }
}

2.!NO_UI.js   文件部分
//在“function main() {” 后 加下列代码

// 截图权限申请 
threads.start(function() {
    var beginBtn;
    if (beginBtn = classNameContains("Button").textContains("立即开始").findOne(2000)) {
        beginBtn.click();
    }
});
sleep(1000);
if (!requestScreenCapture(false)) {
    toastLog("请求截图失败");
    exit();
}
threads.shutDownAll(); //停止所有通过threads.start()启动的子线程

**Comment by cloudy059** [comment]
制作了个logo，也希望采纳
![icon](https://user-images.githubusercontent.com/72952020/104087259-5be2db80-5299-11eb-92d8-eafc251b73f7.png)

**Comment by Ivan-cn** [comment]
这就是james-bond-007的代码，可用优化一下使用。@wanghuisenior，你这些代码出处应该写一下，个人建议No-ui还是不放了，之前的输入用户名和密码处应该用findOne，目前听说有人用来做黑产卖钱，已经远离了学习研究的了

**Comment by wanghuisenior** [comment]
试了试能用，非常感谢

**Comment by 85524365** [comment]
老大，加进去吧，期盼

**Comment by zxc205** [comment]
有没有小白学习的地方😂😂
