### ISSUE TITLE
获取积分不正常，第三步就卡住了（Android9 MIUI11.0.5稳定版）

### ISSUE THREAD

**Issue by wdqzgx** [wanghuisenior/auto_xxqg#5]
**另：目录下除了jsoup-1.12.1.jar和tiku.db，还要什么支持？**

![QQ图片20200621015330](https://user-images.githubusercontent.com/60935511/85208349-26f55280-b362-11ea-80d3-90b836bd35e2.jpg)

**Comment by wanghuisenior** [comment]
> **另：目录下除了jsoup-1.12.1.jar和tiku.db，还要什么支持？**
> 
> ![QQ图片20200621015330](https://user-images.githubusercontent.com/60935511/85208349-26f55280-b362-11ea-80d3-90b836bd35e2.jpg)

你就不能看下日志吗，点击本地频道我写的点击河南，你是广西的改成广西的不就行了
